version: "3"

services:
  db:
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    env_file:
      - .env
  backend:
    container_name: fastapi
    build: .
    volumes:
      - .:/backend/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db